### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by eric-f** [UBC-MDS/DSCI_522_payla_rzitomer#23]
__Mechanics__
- [x] Could have explained a bit more on how to run the scripts and the dependencies among the scripts, e.g. whose output is whose expected input. Maybe add some in-line comments to these two code chunks?

__Report__
- [x] Would be nice to present some summary statistics for the shortlisted features in the Data Cleaning and Feature Selection section
- [x] Would be nice to replace the variable names in the figures and tables with names in English. The snake_case doesn't look very polished in a report.

__Extra__
- [x] For Figures 1, I wonder if you can make the width of the bar proportion to the number of wines.
- [x] Text in Figure 6 is too small to read. Yet, I guess it will be time consuming to write your own function to visualize the tree (?) I wonder if there are any options for what to show in each node...

**Comment by aylapear** [comment]
I have looked at the different options for visualizing the tree and you can only control whether two of the items (impurity and class)  appear in the visualization. Unfortunately removing them does not increase the size of the remaining text. There is no parameter to control the text size in the function we are using and it would be a lot work/time to write our own function to create the visualization.  I will try adjusting the image size in the report to see if we can make it display a bit larger but due to its size I don't think it can increase much. If we went to depth 2 we could increase the image size but since we are predicting the top 3 parameters it is nice to have them all appear in the decision tree diagram.

**Comment by aylapear** [comment]
I have changed the output of the figure to remove the snake case. Before it read country_Canada, now it reads country Canada. I left category to ensure there is no confusion of what the item is, an example is there is the campaign region in France as well as it is a wine variety.

**Comment by rzitomer** [comment]
We explained more about dependencies by adding inline comments the the code chunks as recommended ab94edba28d2d9b7be2831077f0823f20ab66023

**Comment by rzitomer** [comment]
We made the widths of the bar proportional to the number of observations in the dataset for both the country and variety graphs. I think it worked pretty well in showing the relative number of observations c7b6c52fafb2ef2e195434d5a56ba988a2324446 007cf1fb54b5199f73159f2dfefe0d75925cc69f

**Comment by rzitomer** [comment]
Added summary statistics for shortlisted variables 54455cacc2fcfc93d11de01f2f2089705de1615b
